import {CSSProperties} from "react";

export const customStyles = {
    container: (provided: CSSProperties) => ({
        ...provided,
        minHeight: '1px',
        textAlign: 'left',
        padding: 0,
        margin: 0,
        border: 'none',
    }),
    control: (provided: CSSProperties) => ({
        ...provided,
        border: '2px solid #cdcdcd',
        borderRadius: '0',
        padding: "0",
        margin: 0,
        minHeight: '1px',
        height: '30px',
    }),
    input: (provided: CSSProperties) => ({
        ...provided,
        fontSize: "0.8em",
        minHeight: '1px',
        padding: 0,
        margin: 0,
        paddingTop: '3px',
        paddingLeft: '6px',
        height: '28px',
    }),
    indicatorsContainer: (provided: CSSProperties) => ({
        ...provided,
        height: '25px',
    }),

    indicatorSeparator: (provided: CSSProperties) => ({
        ...provided,
        margin: '4px 3px 0 0',
        width: '2px',
        minHeight: "10px",
        height: '18px',
    }),
    dropdownIndicator: (provided: CSSProperties) => ({
        ...provided,
        minHeight: '1px',
        padding: 0,
        margin: 0,
        marginBottom: '2px',
        marginRight: '4px',
        color: '#b8b6b6',
        width: '15px',
        height: '15px',
    }),
    clearIndicator: (provided: CSSProperties) => ({
        ...provided,
        color: '#b8b6b6',
        minHeight: '1px',
        padding: 0,
        margin: 0,
        marginBottom: '2px',
        marginRight: '4px',
        height: '15px',
        width: '15px',
    }),
    valueContainer: (provided: CSSProperties) => ({
        ...provided,
        padding: 0,
        paddingLeft: '2px',
        margin: 1,
        minHeight: '1px',
        height: '30px',
        paddingTop: '2px',
    }),
    singleValue: (provided: CSSProperties) => ({
        ...provided,
        minHeight: '1px',
        height: '30px',
        paddingTop: '3px',
        paddingLeft: '8px',
        fontSize: '0.8em',
    }),
    list: (provided: CSSProperties) => ({
        ...provided,
        height: '20px',
        fontSize: '0.8em',
    }),
    placeholder: (provided: CSSProperties) => ({
        ...provided,
        fontSize: '0.8em',
        height: '30px',
        paddingTop: '3px',
        paddingLeft: '6px',
    }),
    noOptionsMessage: (provided: CSSProperties) => ({
        ...provided,
        fontSize: '0.8em'
    }),
    option: (provided: CSSProperties) => ({
        ...provided,
        fontSize: '0.8em',
    }),
};